/*
 * generated by Xtext
 */
package org.xtext.example.survey;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SurveyRuntimeModule extends org.xtext.example.survey.AbstractSurveyRuntimeModule {

}
